kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc0001
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
